# fly.toml app configuration file generated for jesse-n8n on 2026-01-31T17:34:08+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jesse-n8n'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_HOST = "jesse-n8n.fly.dev"
  N8N_PORT = "5678"
  N8N_PROTOCOL = "https"
  # Recommended by n8n to clear deprecation warnings
  DB_SQLITE_POOL_SIZE = "4"
  N8N_RUNNERS_ENABLED = "true"
  N8N_BLOCK_ENV_ACCESS_IN_NODE = "false"
  N8N_GIT_NODE_DISABLE_BARE_REPOS = "true"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
