app = 'jesse-n8n'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  image = 'n8nio/n8n:latest'

[env]
  EXECUTIONS_DATA_MAX_AGE = '168'
  EXECUTIONS_DATA_PRUNE = 'true'
  GENERIC_TIMEZONE = 'Asia/Jakarta'
  N8N_DIAGNOSTICS_ENABLED = 'false'
  N8N_HIRING_BANNER_ENABLED = 'false'
  N8N_HOST = 'jesse-n8n.fly.dev'
  N8N_PORT = '5678'
  N8N_PROTOCOL = 'https'
  TINI_SUBREAPER = 'true'
  WEBHOOK_URL = 'https://jesse-n8n.fly.dev'

[[mounts]]
  source = 'n8n_data'
  destination = '/home/node/.n8n'

[[services]]
  protocol = 'tcp'
  internal_port = 5678
  processes = ['app']
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024